### ISSUE TITLE
MVP support for NFT

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-nft-indexer#31]
- Drop support for snapshot
- Drop the indexer
- Keep the API server
- Replace the watch endpoint with the probe endpoint.
  - The probe endpoint blocks large NFT collection with `getNFTsForCollection`. If the response has page key, it implies the collection may be too large.
- Rewrite the nfts endpoint
  - It always read from the table `eth_nft_owner` of the database to return a response
  - It determines whether it needs to update `eth_nft_owner` before returning a response
    - It does so by storing `nft_owner (blockchain, network, address, last_sync_at)` 
  - It takes `owner_address` and `contract_ids`.
  - It calls `getNFTs` for at most 5 times (configurable) to get the NFTs owned by a given address
  - It calls `getAssetTransfers` with `to_address` and the intersection of (`contract_ids` and the response of `getNFTs`) at most 5 times to upsert `eth_nft_owner`.

**Comment by hochiw** [comment]
I think we use `getOwnersForCollection` for the collection probing api
